import React, { useEffect, useState } from 'react';
import { useChat } from '@/context/ChatContext';
import { useData } from '@/context/DataContext';
import axios from 'axios';
import ReactMarkdown from 'react-markdown';
import { Printer, FileText, Loader2 } from 'lucide-react';

export function ReportView() {
  const { messages } = useChat();
  const { fileName } = useData();
  const [report, setReport] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const generateReport = async () => {
    if (messages.length === 0) return;
    setLoading(true);
    try {
        const response = await axios.post('/api/report', { conversation: messages });
        setReport(response.data.report);
    } catch (e) {
        console.error(e);
    } finally {
        setLoading(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <div className="flex items-center justify-between print:hidden">
        <h1 className="text-2xl font-bold text-slate-900 dark:text-white">Analysis Report</h1>
        <div className="flex gap-2">
            <button 
                onClick={generateReport}
                disabled={loading || messages.length === 0}
                className="flex items-center gap-2 px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 disabled:opacity-50 transition-colors"
            >
                {loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <FileText className="h-4 w-4" />}
                Generate Summary
            </button>
            <button 
                onClick={handlePrint}
                disabled={!report && messages.length === 0}
                className="flex items-center gap-2 px-4 py-2 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-300 rounded-lg hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors"
            >
                <Printer className="h-4 w-4" />
                Print
            </button>
        </div>
      </div>

      <div className="bg-white dark:bg-slate-950 p-8 rounded-2xl shadow-sm border border-slate-200 dark:border-slate-800 print:shadow-none print:border-none print:p-0">
        <div className="mb-8 border-b border-slate-100 dark:border-slate-800 pb-6">
            <h1 className="text-3xl font-bold text-slate-900 dark:text-white mb-2">Data Analysis Report</h1>
            <div className="flex items-center gap-4 text-sm text-slate-500">
                <span>Source: {fileName || 'Unknown'}</span>
                <span>•</span>
                <span>Date: {new Date().toLocaleDateString()}</span>
            </div>
        </div>

        {report && (
            <div className="mb-8 prose dark:prose-invert max-w-none bg-indigo-50 dark:bg-indigo-900/10 p-6 rounded-xl border border-indigo-100 dark:border-indigo-900/30">
                <h3 className="text-indigo-900 dark:text-indigo-300 font-semibold mb-2 flex items-center gap-2">
                    <FileText className="h-4 w-4" />
                    Executive Summary
                </h3>
                <ReactMarkdown>{report}</ReactMarkdown>
            </div>
        )}

        <div className="space-y-8">
            <h3 className="text-lg font-semibold text-slate-900 dark:text-white">Detailed Analysis Log</h3>
            {messages.filter(m => m.role === 'assistant').map((msg, idx) => (
                <div key={msg.id} className="border-l-2 border-slate-200 dark:border-slate-800 pl-4 py-2 break-inside-avoid">
                    <div className="text-xs text-slate-400 uppercase tracking-wider mb-1">Insight #{idx + 1}</div>
                    <div className="prose dark:prose-invert max-w-none text-sm">
                        <ReactMarkdown>{msg.content}</ReactMarkdown>
                    </div>
                    {msg.type === 'visualization' && (
                        <div className="mt-4 p-4 border border-slate-100 dark:border-slate-800 rounded-lg bg-slate-50 dark:bg-slate-900/50 print:break-inside-avoid">
                            <div className="text-xs text-center text-slate-400 mb-2">[Chart: {msg.visualizationConfig?.title || 'Visualization'}]</div>
                            {/* Note: Charts might not print perfectly without specific CSS, but this is a start */}
                        </div>
                    )}
                </div>
            ))}
        </div>
        
        <div className="mt-12 pt-6 border-t border-slate-100 dark:border-slate-800 text-center text-xs text-slate-400">
            Generated by DataWhisper AI Platform
        </div>
      </div>
    </div>
  );
}
